name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use Node.js 16 for better compatibility

    - name: Print environment variables
      run: echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}"

    - name: Install dependencies
      run: npm install

    - name: Build project
      env:
        VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      run: |
        # Create a .env.production file with the API key
        echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" > .env.production
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
