name: Deploy static content to Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env.production file
        run: |
          echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" > .env.production
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env.production

      - name: Build
        run: npm run build

      - name: Move build files to docs
        run: |
          rm -rf ./docs
          mv ./dist ./docs

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin main
